### ISSUE TITLE
Does not open through file manager

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/io.github.celluloid_player.Celluloid#1]
I'd like to use this instead of VLC for better desktop integration, but any time I try to just open a media file from the file manager, it never opens. I can open a file via command line. And if Celluloid is already open, opening a media file from the file manager works fine. But when Celluloid is not already open, it doesn't work.

I'm using Xubuntu 18.04.2, and my file manager is Thunar. If I kill every instance of thunar and reopen it via a terminal to get some output, there's no output when I try to open a file. xdg-open also doesn't have any output when I try to open a file.

What should I do to try and diagnose this?

**Comment by TingPing** [comment]
I'll start by saying it works fine here (GNOME if relevant).

Firstly lets ensure the file associations are set up correctly, for example if you are opening an mp4 file: `gio mime video/mp4` should return `Default application for “video/mp4”: io.github.celluloid_player.Celluloid.desktop` and `gio open $an_mp4_file` should work.

**Comment by TiZ-EX1** [comment]
File associations are set up correctly. Same behavior when using `gio`, both in that Celluloid does not open, and that if Celluloid is already open, it will play the file.

```
NKU18R0311 mus $ gio mime audio/flac
Default application for “audio/flac”: io.github.celluloid_player.Celluloid.desktop
Registered applications:
	io.github.celluloid_player.Celluloid.desktop
	org.videolan.VLC.desktop
	io.github.quodlibet.QuodLibet.desktop
	org.audacityteam.Audacity.desktop
Recommended applications:
	io.github.celluloid_player.Celluloid.desktop
	org.videolan.VLC.desktop
	io.github.quodlibet.QuodLibet.desktop
	org.audacityteam.Audacity.desktop
NKU18R0311 mus $ gio open Take.flac
NKU18R0311 mus $
```

I am on Xubuntu 18.04.2, which is stuck at Flatpak 1.0.8. Do you think that may be relevant?

**Comment by TiZ-EX1** [comment]
Yikes, 1.0.8 is WAY behind. I installed 1.4.2 from the PPA, but it didn't seem to make any difference.

**Comment by Eonfge** [comment]
I have this too, tested it today, and I think it's because of the .desktop file

If i do
``` /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=celluloid --file-forwarding io.github.celluloid_player.Celluloid ```

the app starts normally. But when I do

``` /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=celluloid --file-forwarding io.github.celluloid_player.Celluloid @@u %U @@ ```.

it gives an error. And to be clear, the bottom version with the extra `@@u %U @@` comes directly from the exec= in the .desktop file

I also tested this with the non-Flatpak version, and there the `@@u %U @@` addition also gives errors. In other words, there is something going wrong with Flatpak, which gives the application an unworkable exec=

**Comment by TingPing** [comment]
The `@@` bits are a flatpak specific thing. If you wanted to run the cli by hand it would be: `flatpak run --file-forwarding @@ file:///path/to/something.mp4 @@`

**Comment by teohhanhui** [comment]
The default setup using `--file-forwarding` is very broken. Many scripts can't work properly like that, e.g. https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

**Comment by HugLifeTiZ** [comment]
I didn't know I had this still open until recently. This issue went away some time ago. My apologies for not staying on top of it.
