### ISSUE TITLE
Dark theme not applied

### ISSUE THREAD

**Issue by firefoxlover** [flathub/io.github.celluloid_player.Celluloid#131]
The app follows the system Theme, the "enable dark theme button" only affects the black bottom bar. It would be cool if the app could just not follow the system theme at all? The top bar is huge and very bright.

Can you show me what access I can disable to make the app either not see the systems GTK theme (this works on KDE too) or preset the dark theme actively?

I could not find an issue about that specifically.

I am using KDE Plasma which applies the Plasma theme to a GTK something theme too. Celluloid follows the Plasmatheme which I set to light.

**Comment by firefoxlover** [comment]
I found the solution:

in KDE Flatpak settings under "Environment" I add this parameter:

```GTK_THEME```

```Adwaita:dark```

Celluloid now uses the dark theme no matter what system theme I use!

**Comment by TingPing** [comment]
Do not set `GTK_THEME`, it is a development setting.

To set a GTK theme: `gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark`

To set dark mode: `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`

**Comment by firefoxlover** [comment]
does this work when just setting it per-app? Because I only want it in the videoplayer, and as there is a setting in its settings I imagine this could be intended behavior

**Comment by TingPing** [comment]
The `GTK_THEME` way is the only per-app way.

**Comment by firefoxlover** [comment]
okay interesting! I am on KDE which automatically adapt the "default" theme to the currently used variant.

I must have changed that, Celluloid does accept that theme.
