### ISSUE TITLE
Build with JavaScript mpv plugin support

### ISSUE THREAD

**Issue by Bananaman** [flathub/io.github.celluloid_player.Celluloid#15]
The libmpv that's included with Ubuntu repos is built without JavaScript. So installing mpv or celluloid via .deb still doesn't give JavaScript support all these years later. Most likely the maintainers just don't realize how to enable JavaScript support.

I thought I'd try this flatpak, but saw that it doesn't have JavaScript support either. Kinda sad since the Windows and Mac versions (of mpv) have it enabled by default and there are plenty of great plugins written in that format.

Anyway, from what I can see, mpv does `#include <mujs.h>` which means that if mujs is in the build-environment paths during package creation, you would successfully create a Celluloid version that can run all the advanced JavaScript mpv plugins that exist.

It seems like it would be enough to make the flatpak build-script download https://github.com/ccxvii/mujs and place its folder in the build PATH.

Here are various JavaScript plugins to test with: https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by TingPing** [comment]
mujs looks simple enough to build, PR for it would be appreciated.

**Comment by Bananaman** [comment]
@TingPing I installed the `flatpak-builder` and SDK to try to help, but I can't, I'm completely lost.

All I know is that when you build mpv manually, there's a `--enable-javascript` waf configure switch which tells it to look for MuJS. I also know that the actual MPV source code does a generic `#include <mujs.h>` so it may be enough / proper that mujs.h exists in the compiler's `#include` search paths without needing `--enable-javascript`. I think the `--enable-javascript` is just to tell it to use the shared library.

Likewise, I am confused about your manifest, because it barely enables *any* mpv build flags such as `--enable-lua` or `--enable-libass` which are both notably missing, yet the manifest downloads their source code separately, so I don't know how that works. I suspect it's doing a static linking via header files, and that MuJS would be installed the same way.

Lastly, I have no idea how to deal with the cleanup directives etc.

So my guess is that the steps needed are:

- Add `https://github.com/ccxvii/mujs` to the manifest to download the source files.
- Be sure that `mujs.h` is in the compiler path. That means static linking, I guess?
- Do cleanup of whatever necessary after that library is built.

But after an hour of trying to figure this out, I give up, I'm too unfamiliar with flatpak building. :-/

**Comment by TingPing** [comment]
MPV automatically detects features, mujs just has to be built first. Sorry I don't have time to handle it myself, somebody might be able to.

**Comment by tinywrkb** [comment]
@Bananaman can you test this? It seems to be working correctly but I don't use the feature.

https://github.com/flathub/io.github.celluloid_player.Celluloid/pull/17#issuecomment-769427533

**Comment by Bananaman** [comment]
@tinywrkb Thank you **so much** for helping! I did a bunch of tests and reported the results in the pull requests. Let's continue the conversation there. :-)
