### ISSUE TITLE
Possible to implement Drag-and-Drop files (DnD Portals API)?

### ISSUE THREAD

**Issue by Arcitec** [flathub/io.github.celluloid_player.Celluloid#16]
The manual "Open a file" dialog works properly in Celluloid and calls the Portals API to be able to see the whole filesystem and get access to whatever file that you tell it to open.

Dragging-and-dropping files doesn't work, though.

However, I read about the "filetransfer" portal which adds drag and drop support to applications. Is this possible to implement in Celluloid, or is it still too early to support it?

Here are the related topics I've found about "drag and drop portals". Seems like it's a very new feature:

https://github.com/flatpak/flatpak/issues/1143

https://github.com/flatpak/xdg-desktop-portal/issues/99

https://github.com/flathub/org.telegram.desktop/issues/23

**Comment by TingPing** [comment]
Should just work in GTK4 once that transition happens.

**Comment by Bananaman** [comment]
@TingPing Ah if I understood that right, the problem is that Celluloid doesn't yet use GTK4? https://github.com/celluloid-player/celluloid.

**Comment by TingPing** [comment]
Correct. That change alone should fix it.

**Comment by vchernin** [comment]
The portal could also be [backported to GTK 3](https://gitlab.gnome.org/GNOME/gtk/-/issues/3094)

**Comment by TingPing** [comment]
I think its a large task that I wouldn't expect to happen.

Its actually probably less friction to port Celluloid to GTK4 and I imagine would happen at some point anyway.

**Comment by TingPing** [comment]
Celluloid uses GTK4 since v0.22 (Nov 5, 2021).
