### ISSUE TITLE
cannot run the app: cannot load libcuda

### ISSUE THREAD

**Issue by fikrillah** [flathub/io.github.celluloid_player.Celluloid#27]
i don't know if it's related, but recently i update the app, and the app cannot run, i tried installing from rpmfusion, it works well

> [user@localhost ~]$ flatpak run io.github.celluloid_player.Celluloid 
VA error: wayland: Wayland roundtrip error: Protokol error (errno 71)
Cannot load libcuda.so.1
Gdk-Message: 19:07:56.006: Error flushing display: Protokol error

**Comment by fikrillah** [comment]
note that i don't use any nvidia hardware, i'm using Intel Core i5-6200U

**Comment by andreas-theo** [comment]
This is a bug with lots (maybe all) of MPV or libmpv based media players. The bug only appears in the Flatpak packages of the programs. There is an open issue (flatpak/flatpak#4289) on the Flatpak repo.

Someone on that bug report suggests that running mpv with --hwdec=vaapi-copy avoids the crash but
`
flatpak run io.github.celluloid_player.Celluloid --mpv-hwdec=vaapi-copy
`
doesn't help with Celluloid.

**Comment by bbhtt** [comment]
Unless you are on nvidia the `Cannot load libcuda.so.1` line is a red herring; the actual error is the one above and below it.

**Comment by qvshuo** [comment]
same problem with Intel i5-8259U

**Comment by andreas-theo** [comment]
This issue has now been [resolved](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/5069) in the freedesktop runtime
