### ISSUE TITLE
What premission is giving this flatpak access to files in ~/Video etc?

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/io.github.celluloid_player.Celluloid#45]
What enables the Celluloid flatpak with its default permissions to see files in my /home and SAMBA shares?  `filesystem=host` is `disabled`, `filesystem=home` is `disabled`, and  the only "other files" enabled are `xdg-run/gvfs`, `xdg-run/gvfsd`, and `xdg-pictures`.  Yet I'm able to watch videos from ~/Videos, ~/Downloads, etc.

Sorry this isn't really an issue but I'm not sure where else to ask.  I'm just looking to understand why it functions this way.  What permission is giving Celluloid access to all the files?

Edit: Just in case this a bug I'm using Flatpak 1.11.2 on PopOS 21.10

**Comment by TingPing** [comment]
It doesn't. This application uses what flatpak calls portals. Which are secure interfaces to the host. The file dialog is ran outside of the sandbox and upon selecting a video only that file is allowed into the sandbox (you can even do so read-only in the bottom corner of the dialog).

**Comment by uncivilgentleman** [comment]
Thank you for taking the time to explain it to me.  I'm impressed with how well the interface works.  I'm able to simply open videos located anywhere from my file manager without any issues. Very cool!
