### ISSUE TITLE
Can't open files from SMB share

### ISSUE THREAD

**Issue by rowbawts** [flathub/io.github.celluloid_player.Celluloid#7]
[This](https://github.com/celluloid-player/celluloid/issues/396) issue from 2018 reports the exact issue I'm having now, Is there still no solution?

Edit: This works in the VLC flatpak if looking there for a solution helps.

**Comment by rowbawts** [comment]
celluloid-player/celluloid#396

**Comment by TingPing** [comment]
> Edit: This works in the VLC flatpak if looking there for a solution helps.

Because its not sandboxed. The issue you linked shows a command to bypass the sandbox.

I'll just be closing this since as I mentioned in the other issue this is not a packaging issue.
