### ISSUE TITLE
Screen tearing during playback.

### ISSUE THREAD

**Issue by tabetai** [flathub/io.github.celluloid_player.Celluloid#9]
VLC installed from flathub doesn't have this problem. Celluloid installed from distro repo also plays video without tearing.

Desktop: Gnome 3.36.2 Distro: Pop!_OS 20.04 LTS
Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 440.82 
Display: x11 server: X.Org 1.20.8

**Comment by TingPing** [comment]
I'll be honest, this isn't going to be debugged here. We have the latest versions of `ffmpeg`, `mpv`, `celluloid`, and probably `gtk3`. If you want to bisect where that problem exists you can report it there.
