### ISSUE TITLE
FFmpeg build does not include GPL-licensed filters

### ISSUE THREAD

**Issue by aidandenlinger** [flathub/io.github.celluloid_player.Celluloid#95]
I'm trying to use the [autocrop script from mpv's repo](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua), which uses [the cropdetect filter](https://ffmpeg.org/ffmpeg-filters.html#cropdetect). However, when run, celluloid displays a `Changing filters failed` message. When running with `--mpv-msg-level="all=warn"`, the console logs

```
celluloid-Message: 15:21:23.340: [cplayer] Option vf-pre: cropdetect doesn't exist.
celluloid-Message: 15:21:24.136: [autocrop] No crop data.
```

I think the issue is that in [ffmpeg's configure script](https://github.com/FFmpeg/FFmpeg/blob/052674f3ce17139de73ea00bb690584240b0478a/configure#L3650), it seems like `cropdetect` only gets included when ffmpeg is built with the GPL license. It looks like this can be achieved by including the `--enable-gpl` flag in the ffmpeg build. I'm definitely not a license expert, but since this is an open source project I don't think there are any issues with enabling this flag to include the missing filters, assuming that ffmpeg's GPL license is included. Are there issues I'm overlooking, or would this project be open to doing that?

**Comment by TingPing** [comment]
I think everything we include is GPL compatible.

I made a patch here if you don't mind testing it once building completes: https://github.com/flathub/io.github.celluloid_player.Celluloid/pull/96

**Comment by aidandenlinger** [comment]
The build at #96 allows the autocrop script to work, there's no more "Changing filters failed" :)
