### ISSUE TITLE
Get verification on Flathub beta

### ISSUE THREAD

**Issue by rashidi77** [flathub/io.github.celluloid_player.Celluloid#98]
There is now a verification method available on Flathub beta website. You can achive it either using your github account or uploading a file in your project website.

**Comment by TingPing** [comment]
Due to some issues with the Flathub website this app can't yet be verified.

Anyway whether or not it will be is up to @gnome-mpv: Would you be interested in marking this package as "verified" officially by the project?

**Comment by gnome-mpv** [comment]
> @gnome-mpv: Would you be interested in marking this package as "verified" officially by the project? I'll do the work to verify it when time comes.

@TingPing: Yes, I'm interested.

**Comment by TingPing** [comment]
I've done the first step here: https://github.com/celluloid-player/celluloid-player.github.io/pull/4

However we will need to wait on some Flathub side fixes before it shows up. It currently doesn't handle the mapping of `celluloid_player` -> `celluloid-player` in the app-id.

**Comment by qoijjj** [comment]
Hi folks, what work is remaining to get this app verified?

**Comment by TingPing** [comment]
Oh thanks for the reminder. I've verified this app.
